---
name: "hello to develop branch"
on:
    push:
        branches:
            - develop
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, develop branch!"